### ISSUE TITLE
Cannot create new CLA versions

### ISSUE THREAD

**Issue by ambv** [edgedb/cla-bot#43]
With EdgeDB 1.2, the following occurs when trying to click "CLONE" in the admin UI (see below for logs):

<img width="1168" alt="Screen Shot 2022-04-10 at 11 57 05" src="https://user-images.githubusercontent.com/55281/162612785-7f130999-2bd8-4d2f-b8f7-9b51cdfc938e.png">

<details>
<summary>Click here to expand logs</summary>
```
2022-04-10T09:51:56.626970+00:00 heroku[router]: at=info method=POST path="/api/agreement-version/96a49432b8b111ec9bf5bfe9ad6c72c4/clone" host=cpython-clabot.herokuapp.com request_id=c78ccf12-240a-47b2-8ebf-294d20b289c2 fwd="85.221.138.177" dyno=web.1 connect=0ms service=203ms status=500 bytes=154 protocol=https
2022-04-10T09:51:56.627129+00:00 app[web.1]: yarn next start -p 25111  !! QueryError: possibly not a distinct set returned by an expression for a computed link 'versions'
2022-04-10T09:51:56.628603+00:00 app[web.1]: yarn next start -p 25111  !!     at RawConnection._parseErrorMessage (/app/node_modules/edgedb/dist/rawConn.js:371:21)
2022-04-10T09:51:56.628744+00:00 app[web.1]: yarn next start -p 25111  !!     at RawConnection._parse (/app/node_modules/edgedb/dist/rawConn.js:714:34)
2022-04-10T09:51:56.629321+00:00 app[web.1]: yarn next start -p 25111  !!     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2022-04-10T09:51:56.629514+00:00 app[web.1]: yarn next start -p 25111  !!     at async RawConnection.fetch (/app/node_modules/edgedb/dist/rawConn.js:970:61)
2022-04-10T09:51:56.629628+00:00 app[web.1]: yarn next start -p 25111  !!     at async ClientConnectionHolder.retryingFetch (/app/node_modules/edgedb/dist/client.js:178:26)
2022-04-10T09:51:56.629731+00:00 app[web.1]: yarn next start -p 25111  !!     at async Client.querySingle (/app/node_modules/edgedb/dist/client.js:485:20)
2022-04-10T09:51:56.629833+00:00 app[web.1]: yarn next start -p 25111  !!     at async /app/.next/server/chunks/1601.js:1517:20
2022-04-10T09:51:56.629933+00:00 app[web.1]: yarn next start -p 25111  !!     at async EdgeDBAgreementsRepository.run (/app/.next/server/chunks/1601.js:1039:14)
2022-04-10T09:51:56.630036+00:00 app[web.1]: yarn next start -p 25111  !!     at async EdgeDBAgreementsRepository.createAgreementVersion (/app/.next/server/chunks/1601.js:1516:12)
2022-04-10T09:51:56.630136+00:00 app[web.1]: yarn next start -p 25111  !!     at async AgreementsHandler.cloneAgreementVersion (/app/.next/server/chunks/1601.js:1004:12) {
2022-04-10T09:51:56.630245+00:00 app[web.1]: yarn next start -p 25111  !!   source: undefined
2022-04-10T09:51:56.630357+00:00 app[web.1]: yarn next start -p 25111  !! }
```
</details>

**Comment by msullivan** [comment]
Looks like the issue is this `UNION` here: https://github.com/edgedb/cla-bot/blob/4d15ed2f233efacd4d6a18c221e3e95dc193d4d4/service/data/edgedb/agreements.ts#L454-L455

Should probably just use `+=` in the UPDATE
