### ISSUE TITLE
CLA bot reports HTTP 500: Internal Server Error

### ISSUE THREAD

**Issue by AA-Turner** [edgedb/cla-bot#50]
e.g. https://github.com/python/peps/pull/2585 with metadata `From: Adam Turner <9087854+aa-turner@users.noreply.github.com>`

From [a thread on the Python discourse forum](https://discuss.python.org/t/internal-server-error-when-trying-to-sign-the-cla/15593/3?u=aa-turner), it might be as simple as a case matching issue (my username is `AA-Turner` but the email is `9087854+aa-turner`).

The web form hard errors to HTTP 500, which makes it very hard to understand exactly what went wrong and where -- ideally that could be improved, although that is a less pertinant issue.

A

**Comment by CAM-Gerlach** [comment]
Seems Adam isn't the only one having issues with this; @terryjreedy reported this was occurring on other issues in https://github.com/python/devguide/pull/898#issuecomment-1158388429

Given this means that such PRs are unmergable aside from repo admins, are marked as check failures and require manual verification, and appears to potentially have a simple solution, this seems to be a pretty critical issue...

**Comment by elprans** [comment]
@ambv, can you take a look at this, or should I?

**Comment by hugovk** [comment]
Here's another report of someone unable to sign the CLA, who has a similar email address: 

* https://github.com/python/devguide/pull/902#issuecomment-1159470383

**Comment by arhadthedev** [comment]
Another occurence: https://github.com/python/cpython/issues/93995.

**Comment by ambv** [comment]
This is the exception, this is due to case significant username matching:
```
2022-06-20T11:22:21.954486+00:00 app[web.1]: yarn next start -p 7895   !!     at SignClaHandler.descriptor.value (/app/.next/server/chunks/1601.js:263:19)
2022-06-20T11:22:21.954537+00:00 app[web.1]: yarn next start -p 7895   !!     at runMicrotasks (<anonymous>)
2022-06-20T11:22:21.954585+00:00 app[web.1]: yarn next start -p 7895   !!     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2022-06-20T11:22:21.954657+00:00 app[web.1]: yarn next start -p 7895   !!     at async SignClaHandler.handleAllMatchingEmails (/app/.next/server/chunks/1601.js:669:9)
2022-06-20T11:22:21.954701+00:00 app[web.1]: yarn next start -p 7895   !!     at async SignClaHandler.signCla (/app/.next/server/chunks/1601.js:699:5)
2022-06-20T11:22:21.954748+00:00 app[web.1]: yarn next start -p 7895   !!     at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/contributors/auth/github/callback.js:125:20)
2022-06-20T11:22:21.954795+00:00 app[web.1]: yarn next start -p 7895   !!     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils.js:102:9)
2022-06-20T11:22:21.954841+00:00 app[web.1]: yarn next start -p 7895   !!     at async Server.handleApiRequest (/app/node_modules/next/dist/server/next-server.js:1064:9)
2022-06-20T11:22:21.954887+00:00 app[web.1]: yarn next start -p 7895   !!     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:951:37)
2022-06-20T11:22:21.954933+00:00 app[web.1]: yarn next start -p 7895   !!     at async Router.execute (/app/node_modules/next/dist/server/router.js:222:32) {
2022-06-20T11:22:21.954979+00:00 app[web.1]: yarn next start -p 7895   !!   internalError: ConflictError: Error: email violates exclusivity constraint
2022-06-20T11:22:21.955025+00:00 app[web.1]: yarn next start -p 7895   !!       at EdgeDBClaRepository.run (/app/.next/server/chunks/1601.js:1037:17)
2022-06-20T11:22:21.955072+00:00 app[web.1]: yarn next start -p 7895   !!       at runMicrotasks (<anonymous>)
2022-06-20T11:22:21.955117+00:00 app[web.1]: yarn next start -p 7895   !!       at processTicksAndRejections (internal/process/task_queues.js:93:5)
2022-06-20T11:22:21.955170+00:00 app[web.1]: yarn next start -p 7895   !!       at async EdgeDBClaRepository.saveCla (/app/.next/server/chunks/1601.js:1098:5)
2022-06-20T11:22:21.955215+00:00 app[web.1]: yarn next start -p 7895   !!       at async SignClaHandler.createCla (/app/.next/server/chunks/1601.js:632:5)
2022-06-20T11:22:21.955262+00:00 app[web.1]: yarn next start -p 7895   !!       at async SignClaHandler.descriptor.value (/app/.next/server/chunks/1601.js:254:18)
2022-06-20T11:22:21.955313+00:00 app[web.1]: yarn next start -p 7895   !!       at async SignClaHandler.handleAllMatchingEmails (/app/.next/server/chunks/1601.js:669:9)
2022-06-20T11:22:21.955358+00:00 app[web.1]: yarn next start -p 7895   !!       at async SignClaHandler.signCla (/app/.next/server/chunks/1601.js:699:5)
2022-06-20T11:22:21.955406+00:00 app[web.1]: yarn next start -p 7895   !!       at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/contributors/auth/github/callback.js:125:20)
2022-06-20T11:22:21.955451+00:00 app[web.1]: yarn next start -p 7895   !!       at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils.js:102:9) {
2022-06-20T11:22:21.955498+00:00 app[web.1]: yarn next start -p 7895   !!     _statusCode: 409,
2022-06-20T11:22:21.955543+00:00 app[web.1]: yarn next start -p 7895   !!     _errorCode: 'Conflict',
2022-06-20T11:22:21.955591+00:00 app[web.1]: yarn next start -p 7895   !!     _internalError: undefined
2022-06-20T11:22:21.955641+00:00 app[web.1]: yarn next start -p 7895   !!   }
2022-06-20T11:22:21.955687+00:00 app[web.1]: yarn next start -p 7895   !! }
```

I have a fix for this that I'll be deploying soon and testing with @AA-Turner.
